DROP DATABASE IF EXISTS TheBasaboostSGdeAlquilerDeVehiculos;
CREATE DATABASE TheBasaboostSGdeAlquilerDeVehiculos;
USE TheBasaboostSGdeAlquilerDeVehiculos;

----- CREACIÓN DE LA BASE DE DATOS -----
--- TABLAS:
CREATE TABLE DEPARTAMENTO(
	id_departamento TINYINT PRIMARY KEY IDENTITY,
	nombre_departamento VARCHAR(35)
);

CREATE TABLE EMPLEADO(
	id_empleado SMALLINT PRIMARY KEY IDENTITY,
	nombre VARCHAR(50) NOT NULL,
	direccion VARCHAR(80) NOT NULL,
	email VARCHAR(40) NOT NULL,
	telefono VARCHAR(14) NOT NULL,
	fecha_contratacion DATE NOT NULL,
	id_puesto TINYINT NOT NULL
);

CREATE TABLE PUESTO_EMPLEADO(
	id_puesto TINYINT PRIMARY KEY IDENTITY,
	puesto VARCHAR(50) NOT NULL
);

--  Intersección Empleado-Departamento
CREATE TABLE EMPLEADO_DEPARTAMENTO (
    id_empleado SMALLINT NOT NULL,
    id_departamento TINYINT NOT NULL,
    PRIMARY KEY (id_empleado, id_departamento),
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado),
    FOREIGN KEY (id_departamento) REFERENCES DEPARTAMENTO(id_departamento)
);

CREATE TABLE MANTENIMIENTO(
	id_mantenimiento VARCHAR(15) PRIMARY KEY,
	matricula varchar(10),
	fecha DATE,
	descripcion VARCHAR(60),
	costo DECIMAL(6,2),
	id_empleado SMALLINT
);

--Tablas que eliminan el muchos a muchos en la tabla "vehiculos"
CREATE TABLE MODELO_VEHICULO (
    id_modelo SMALLINT PRIMARY KEY,
    modelo VARCHAR(50) NOT NULL
);

CREATE TABLE MARCA_VEHICULO (
    id_marca SMALLINT PRIMARY KEY,
    marca VARCHAR(30) NOT NULL
);

CREATE TABLE TIPO_VEHICULO (
    id_tipo SMALLINT PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL
);

CREATE TABLE ESTADO_VEHICULO (
    id_estado_v SMALLINT PRIMARY KEY,
    estado_v VARCHAR(30) NOT NULL
);

CREATE TABLE VEHICULOS (
    matricula VARCHAR(10) PRIMARY KEY,
    id_marca SMALLINT NOT NULL,
    id_modelo SMALLINT NOT NULL,
    anio DATE NOT NULL,
    id_tipo SMALLINT NOT NULL,
    precio_diario DECIMAL(8,2) NOT NULL,
    id_estado_v SMALLINT NOT NULL,
    id_empleado SMALLINT NOT NULL,
);

CREATE TABLE CLIENTE(
	id_cliente VARCHAR(15) PRIMARY KEY,
	nombre VARCHAR(50),
	direccion VARCHAR(80),
	email varchar(40),
	num_licencia VARCHAR(12),
	telefono VARCHAR(13),
	fecha_registro DATE
);

CREATE TABLE RESERVA(
    id_reserva VARCHAR(15) PRIMARY KEY,
    id_cliente VARCHAR(50),
    matricula VARCHAR(50),
    fecha_inicio_alquiler DATE,
    fecha_fin_alquiler DATE,
    id_estado_r VARCHAR(12),
    kilometraje_estimado INT
);

CREATE TABLE ESTADO_RESERVA(
    id_estado_r VARCHAR(12) PRIMARY KEY,
    estado_v VARCHAR(40)
);

CREATE TABLE SERVICIO_RESERVA (
    id_reserva VARCHAR(15) NOT NULL,
    id_servicio_adicional VARCHAR(15) NOT NULL,
    PRIMARY KEY (id_reserva, id_servicio_adicional)
);

-- Intersección Reserva-Servicios Adicionales
CREATE TABLE SERVICIOS_ADICIONALES(
    id_servicio_adicional VARCHAR(15) PRIMARY KEY,
    nombre VARCHAR(35),
    costo DECIMAL(7, 2),
    descripcion VARCHAR(80)
);

CREATE TABLE PAGO (
    id_pago VARCHAR(15) PRIMARY KEY,
    id_reserva VARCHAR(15),	
    monto DECIMAL(8, 2),
    fecha_pago DATE,
    id_metodo_pago VARCHAR(10)	
);

CREATE TABLE METODO_PAGO (
    id_metodo_pago VARCHAR(10) PRIMARY KEY,
    metodo_pago VARCHAR(30)
);

-- FOREIGN KEYS:
-- PARA LA TABLA "EMPLEADO"
ALTER TABLE EMPLEADO ADD FOREIGN KEY(id_puesto) REFERENCES PUESTO_EMPLEADO(id_puesto);

-- PARA LA TABLA INTERMEDIA "EMPLEADO_DEPARTAMENTO"
ALTER TABLE EMPLEADO_DEPARTAMENTO ADD FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado) ON DELETE CASCADE;
ALTER TABLE EMPLEADO_DEPARTAMENTO ADD FOREIGN KEY (id_departamento) REFERENCES DEPARTAMENTO(id_departamento) ON DELETE CASCADE;	

ALTER TABLE VEHICULOS ADD FOREIGN KEY (id_marca) REFERENCES MARCA_VEHICULO(id_marca) ON DELETE CASCADE;
ALTER TABLE VEHICULOS ADD FOREIGN KEY (id_modelo) REFERENCES MODELO_VEHICULO(id_modelo) ON DELETE CASCADE;
ALTER TABLE VEHICULOS ADD FOREIGN KEY (id_tipo) REFERENCES TIPO_VEHICULO(id_tipo) ON DELETE CASCADE;
ALTER TABLE VEHICULOS ADD FOREIGN KEY (id_estado_v) REFERENCES ESTADO_VEHICULO(id_estado_v) ON DELETE CASCADE;

-- PARA LA TABLA "MANTENIMIENTO"
ALTER TABLE MANTENIMIENTO ADD FOREIGN KEY(id_empleado) REFERENCES EMPLEADO(id_empleado) ON DELETE CASCADE; 
ALTER TABLE MANTENIMIENTO ADD FOREIGN KEY(matricula) REFERENCES VEHICULOS(matricula) ON DELETE CASCADE; 

-- PARA LA TABLA "RESERVA"
ALTER TABLE RESERVA ADD FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id_cliente) ON DELETE CASCADE;
ALTER TABLE RESERVA ADD FOREIGN KEY (matricula) REFERENCES VEHICULO(matricula) ON DELETE CASCADE;
ALTER TABLE RESERVA ADD FOREIGN KEY (id_estado_r) REFERENCES ESTADO_RESERVA(id_estado_r) ON DELETE CASCADE;

--PARA LA TABLA "PAGO"
ALTER TABLE PAGO ADD FOREIGN KEY (id_reserva) REFERENCES RESERVA(id_reserva) ON DELETE CASCADE;
ALTER TABLE PAGO ADD FOREIGN KEY (id_metodo_pago) REFERENCES METODO(id_metodo_pago) ON DELETE CASCADE;

-- PARA LA TABLA INTERMEDIA "SERVICIO_RESERVA"
ALTER TABLE SERVICIO_RESERVA ADD FOREIGN KEY (id_reserva) REFERENCES RESERVA(id_reserva) ON DELETE CASCADE;
ALTER TABLE SERVICIO_RESERVA ADD FOREIGN KEY (id_servicio_adicional) REFERENCES SERVICIOS_ADICIONALES(id_servicio_adicional) ON DELETE CASCADE;


--Inserciones
